version: '3.4'

services:
  mongodb:
    image: mongo:5.0
    container_name: mongodb
    ports:
      - 27020:27017
    volumes:
      - ~/mongodb-data/mongo:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=citizix
      - MONGO_INITDB_ROOT_PASSWORD=S3cret
    restart: always
  app:
    build:
      # context: .
      context: https://github.com/AlexLitvein/GBProjectTeam_backend.git#main
      dockerfile: https://github.com/AlexLitvein/GBProjectTeam_backend.git#main/dev.dockerfile

    container_name: serv
    environment:
      DATABASE_URL: mongodb://citizix:S3cret@mongodb:27017/
      JWT_SECRET: my-secret
    ports:
      - 80:3333
    restart: always
    links:
      - mongodb
